### ISSUE TITLE
Preferred Attribution Method?

### ISSUE THREAD

**Issue by schaufja** [Paranoid-AF/Jsona#2]
I'm working on a plugin for Sven Co-op that saves players and their item_inventories based on named "saves" and have used Jsona for most of the core data handling.

Would you prefer I include Jsona as it appears in this repo (e.g. with all files including README.md) in a sub-folder within my plugin, or would you rather I direct anyone interested in my plugin here to get Jsona and install it themselves?
Either way I would be including your name in the credits for my own plugin documentation and any maps that utilize it.

I can work with either option but the first would be the preferred of the two.

Thanks for such a great plugin/library!
The Seventh

**Comment by Paranoid-AF** [comment]
Hey, thanks for reaching out!

Considering the fact that Sven Co-op doesn’t (and probably shouldn’t) have a package manager for AngelScript, it would be a disaster to manage dependency versions. So personally I recommend to include it as a subfolder. 

In this case, you could use [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for a better experience.

As for me, both ways are OK. These are just my suggestions. To be honest, I don’t quite care about the details in usage of my work. As long as my work is being used for a good purpose and better yet following its license, I would be happy for the fact that it helps.

Happy coding!
